dist: focal
language: python
python:
  - "3.8"

install:
  - sudo apt-get -y install libsqlite3-dev gcc
  - pip install pipenv
  - pipenv install --dev --deploy --system
  - wget 'https://www.sqlite.org/contrib/download/?get=25' -O extension-functions.c
  - gcc -fPIC -shared extension-functions.c -o libsqlitefunctions.so -lm

script:
  - pytest
