# Generated by Django 2.0.3 on 2018-03-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=12, primary_key=True, serialize=False)),
                ('epoch', models.IntegerField()),
                ('time', models.FloatField(db_column='Time')),
                ('view', models.IntegerField(db_column='View')),
                ('comment', models.IntegerField(db_column='Comment')),
                ('mylist', models.IntegerField(db_column='Mylist')),
            ],
            options={
                'db_table': 'chart',
            },
        ),
        migrations.CreateModel(
            name='Idtag',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=12, primary_key=True, serialize=False)),
                ('tagname', models.CharField(db_column='tagName', max_length=60)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'IDtag',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.CharField(db_column='ID', max_length=12, primary_key=True, serialize=False)),
                ('validity', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('iscomplete', models.IntegerField(db_column='isComplete')),
                ('postdate', models.DateTimeField(blank=True, null=True)),
                ('analyzegroup', models.IntegerField(blank=True, db_column='analyzeGroup', null=True)),
            ],
            options={
                'db_table': 'status',
            },
        ),
        migrations.CreateModel(
            name='Tagcolor',
            fields=[
                ('tagname', models.CharField(db_column='tagName', max_length=60, primary_key=True, serialize=False)),
                ('color', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
            options={
                'db_table': 'tagColor',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tagcolor',
            unique_together={('tagname', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='idtag',
            unique_together={('id', 'tagname')},
        ),
        migrations.AlterUniqueTogether(
            name='chart',
            unique_together={('id', 'epoch')},
        ),
    ]
