# Generated by Django 2.0.3 on 2018-04-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20180417_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idtag',
            name='id',
            field=models.ForeignKey(db_column='ID', max_length=12, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.Status'),
        ),
    ]
