# Generated by Django 2.0.5 on 2018-06-01 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20180421_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongIndex',
            fields=[
                ('id', models.ForeignKey(db_column='ID', max_length=12, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='movie.Status')),
                ('value0', models.FloatField()),
                ('value1', models.FloatField()),
                ('value2', models.FloatField()),
                ('value3', models.FloatField()),
                ('value4', models.FloatField()),
                ('value5', models.FloatField()),
                ('value6', models.FloatField()),
                ('value7', models.FloatField()),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'song_index',
            },
        ),
    ]
