# Generated by Django 2.0.5 on 2018-06-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('movie', '0005_analyzequeue'), ('movie', '0006_auto_20180601_1317')]

    dependencies = [
        ('movie', '0004_songindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzeQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('status', models.IntegerField()),
                ('queued_date', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(db_column='movie_id', max_length=12, on_delete=django.db.models.deletion.CASCADE, to='movie.Status')),
            ],
            options={
                'db_table': 'analyze_queue',
            },
        ),
    ]
