# Generated by Django 2.0.6 on 2018-11-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_auto_20180617_0135_squashed_0009_auto_20180617_1243'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['view'], name='chart_View_ea26b2_idx'),
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['view', 'status'], name='chart_View_bf9b21_idx'),
        ),
    ]
