# Generated by Django 2.0.6 on 2018-11-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_auto_20181115_0019'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chart',
            name='chart_View_bf9b21_idx',
        ),
        migrations.AddIndex(
            model_name='chart',
            index=models.Index(fields=['status', 'view'], name='chart_status__5ce88b_idx'),
        ),
    ]
