# Generated by Django 2.0.6 on 2018-12-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('movie', '0011_auto_20181211_1804'), ('movie', '0012_auto_20181211_1910')]

    dependencies = [
        ('movie', '0010_auto_20181130_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='status',
            name='score_status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
