"""
g
Django settings for UtakoSite project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

from pathlib import Path
import json

C = {}
config = Path('/etc/utako/config')
for fpath in config:
    with open(fpath) as f:
        C[fpath.name] = f.read()

S = {}
secret = Path('/etc/utako/secret')
for fpath in secret:
    with open(fpath) as f:
        S[fpath.name] = f.read()

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = S['secret_key']

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': C['db.name'],
        'USER': C['db.user'],
        'PASSWORD': S['db.pass'],
        'HOST': C['db.host'],
    }
}

ALLOWED_HOSTS = json.dumps(C['allowed_hosts'])
DEBUG = True if C['debug'] == 'True' else False

EMAIL_HOST = C['email.host']
EMAIL_PORT = C['email.port']
EMAIL_HOST_USER = C['email.user']
EMAIL_HOST_PASSWORD = S['email.pass']

GOOGLE_AD_CLIENT= C['google.ad_client']
GOOGLE_ANALYTICS= C['google.analytics']

SOCIAL_AUTH_TWITTER_KEY = S['social_auth.twitter.key']
SOCIAL_AUTH_TWITTER_SECRET = S['social_auth.twitter.secret']
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = S['social_auth.google.key']
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = S['social_auth.google.secret']

STATIC_URL = C['static_url']
