"""
Django settings for UtakoSite project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5q)%iml%1h$f1t=&+q@-&1e0k^nbn=ha@wi4k!1d@utx%b6_j7'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }
}

ALLOWED_HOSTS = ['localhost',]
INTERNAL_IPS = ['localhost',]
DEBUG = False

GOOGLE_AD_CLIENT=""
GOOGLE_ANALYTICS=""
STATIC_URL = '/static/'
